name: opsgpt_warehouse
version: 0.1.0
config-version: 2

profile: opsgpt_warehouse

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  opsgpt_warehouse:
    +materialized: view
